FROM karya-root:latest

WORKDIR /usr/src/karya/backend

COPY ../backend /usr/src/karya/backend 
COPY ../common /usr/src/karya/common 
COPY ../core /usr/src/karya/core
COPY ../utils /usr/src/karya/utils

EXPOSE 5000
