# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: ‘**\backend.env’
    TargetFolder: '$(Build.SourcesDirectory)/server/backend/.env'

- script: |
    cat '$(Build.SourcesDirectory)/server/backend/.env'
  displayName: 'Run a multi-line script'
