FROM karya-base:latest
WORKDIR /usr/src/karya/box 

COPY ../box/ /usr/src/karya/box/
COPY ../common /usr/src/karya/common 
COPY ../core /usr/src/karya/core
COPY ../utils /usr/src/karya/utils

EXPOSE 8000
