export enum BulkTransactionTaskStatus {
    INITIALISED = "INITIALISED",
    SERVER_BULK_TRANSACTION_QUEUE = "SERVER_BULK_TRANSACTION_QUEUE",
    PARTIAL_PROCESSED = "PARTIAL_PROCESSED",
    TRANSACTIONS_PROCESSED = "TRANSACTIONS_PROCESSED",
    FAILED = "FAILED"
}