export enum BulkTransactionTaskStatus {
    INITIALISED = "INITIALISED",
    SERVER_BULK_TRANSACTION_QUEUE = "SERVER_BULK_TRANSACTION_QUEUE",
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS",
    SUCESS = "SUCCESS",
    FAILED = "FAILED"
}