export default {
  SUBMIT_TASK_INPUT_FILE: [['ADMIN'], ['WORK_PROVIDER']],
  GET_TASK_IO_FILES: [['ADMIN'], ['WORK_PROVIDER']],
  CREATE_OUTPUT_FILE: [['ADMIN'], ['WORK_PROVIDER']],
  CREATE_TASK: [['ADMIN'], ['WORK_PROVIDER']],
  EDIT_TASK: [['ADMIN'], ['WORK_PROVIDER']],
  CREATE_TASK_LINK: [['ADMIN'], ['WORK_PROVIDER']],
  GET_ALL_TASK_LINKS: [['ADMIN'], ['WORK_PROVIDER']],
  SUBMIT_LANGUAGE_ASSETS: [['ADMIN'], ['WORK_PROVIDER']],
  MARK_TASK_COMPLETE: [['ADMIN'], ['WORK_PROVIDER']],
  DISABLE_WORKER: [['ADMIN']],
  GENERATE_WORKERS: [['ADMIN']],
  GET_WORKER_TASK: [['ADMIN']],
};
